sudo: required
dist: trusty
# Force travis to use its minimal image with default Python settings
language: generic
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - gm130s@gmail.com
env:
  matrix:
    - HOSTNAME=130s-serval
    - HOSTNAME=130s-t440s
    - HOSTNAME=tork-kudu1
before_script:
  - export DISPLAY=:99.0
  - export REPOSITORY_NAME="${TRAVIS_REPO_SLUG##*/}"
script:
  - ./script/install_ubuntu_common.sh
#  - source /opt/ros/$CI_ROS_DISTRO/setup.bash
after_script:
  - ./test/test_overall_travis.sh
