sudo: required
dist: trusty
# Force travis to use its minimal image with default Python settings
language: generic
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - gm130s@gmail.com
env:
  matrix:
    - HOSTNAME=130s-serval
    - HOSTNAME=130s-t440s
    - HOSTNAME=tork-kudu1
install:
  - sudo ./install_ubuntu_common.bash
#script:
#  - source /opt/ros/$CI_ROS_DISTRO/setup.bash
